version: '3.9'

services:
    app:
        image: rodrigo270695/resitrack-app:v1
        container_name: resitrack-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel

    db:
        image: mysql
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: bd_recitrack_d
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - laravel

networks:
    laravel:

volumes:
    dbdata:
